type Consulta {
    id: ID!
    paciente: Paciente!
    medico: Medico!
    hospital: Hospital!
    data: String!
    horario: String!
    status: StatusConsulta!
    criadoEm: String!
}

type Paciente {
    id: ID!
    nome: String!
    email: String!
    telefone: String
}

type Medico {
    id: ID!
    nome: String!
    email: String!
}

type Hospital {
    id: ID!
    nome: String!
}

enum StatusConsulta {
    AGENDADA
    CONFIRMADA
    CANCELADA
    AUSENTE
    REALIZADA
}

type Query {
    historicoPorPaciente(pacienteId: ID!): [Consulta]
    consultasFuturasPorPaciente(pacienteId: ID!): [Consulta]
    consultasPassadasPorPaciente(pacienteId: ID!): [Consulta]
    consultaPorId(id: ID!): Consulta
}
